import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="flex flex-row gap-5 items-start">
          <Sidebar />
          <section className="grow mt-5 m-5 relative space-y-10 ml-[250px]">
            <Navbar />
            <div className="w-[calc(100%-1rem)]"> {children}</div>
          </section>
        </section>
      </body>
      {/* <body className={inter.className}>
        <section>
          <section className="flex flex-row gap-5 relative items-start flex-nowrap ">
            <Sidebar />
            <section className="grow lg:mr-5 mt-5 m-5 relative space-y-10">
              <Navbar />{" "}
              <div className="w-[calc(100%-1rem)] sticky"> {children}</div>
            </section>
          </section>
        </section>
      </body> */}
    </html>
  );
}
